# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-18 16:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GpuStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField(verbose_name='GPU no.')),
                ('hashrate', models.DecimalField(decimal_places=3, max_digits=9, verbose_name='hashrate (MH/s)')),
                ('temp', models.SmallIntegerField(verbose_name='temperature (C)')),
                ('fan', models.SmallIntegerField(verbose_name='fan (%)')),
            ],
            options={
                'verbose_name': 'GPU status',
                'verbose_name_plural': 'GPU statuses',
            },
        ),
        migrations.CreateModel(
            name='MinerStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('online', models.BooleanField(default=False, verbose_name='online')),
                ('ping', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ping (ms)')),
                ('version', models.CharField(blank=True, max_length=255, verbose_name='version')),
                ('runtime', models.IntegerField(blank=True, null=True, verbose_name='uptime (mins)')),
                ('hashrate', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True, verbose_name='hashrate (MH/s)')),
                ('shares', models.IntegerField(blank=True, null=True, verbose_name='shares')),
                ('rej_shares', models.IntegerField(blank=True, null=True, verbose_name='rejected shares')),
                ('pool', models.CharField(blank=True, max_length=255, verbose_name='pool')),
                ('invalid_shares', models.IntegerField(blank=True, null=True, verbose_name='invalid shares')),
                ('pool_switches', models.IntegerField(blank=True, null=True, verbose_name='pool switches')),
                ('gpus_online', models.IntegerField(blank=True, null=True, verbose_name='GPUs online')),
                ('gpus_offline', models.IntegerField(blank=True, null=True, verbose_name='GPUs offline')),
                ('max_temp', models.IntegerField(blank=True, null=True, verbose_name='max GPU temp')),
            ],
            options={
                'verbose_name': 'miner status',
                'verbose_name_plural': 'miner statuses',
                'ordering': ['-created_at', 'miner'],
            },
        ),
        migrations.CreateModel(
            name='Rig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255, verbose_name='hostname/IP')),
                ('port', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(65535)], verbose_name='port')),
                ('password', models.CharField(blank=True, max_length=60, verbose_name='password')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='display name')),
                ('active_gpus', models.PositiveSmallIntegerField(default=6, verbose_name='# of active GPUs')),
                ('enabled', models.BooleanField(default=True, verbose_name='monitoring enabled')),
            ],
            options={
                'verbose_name': 'rig',
                'verbose_name_plural': 'rigs',
                'ordering': ['name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='rig',
            unique_together=set([('host', 'port')]),
        ),
        migrations.AddField(
            model_name='minerstatus',
            name='miner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Rig', verbose_name='rig'),
        ),
        migrations.AddField(
            model_name='gpustatus',
            name='miner_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.MinerStatus', verbose_name='miner status record'),
        ),
    ]
