# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-19 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gpustatus',
            options={'ordering': ['-miner_status', 'number'], 'verbose_name': 'GPU status', 'verbose_name_plural': 'GPU statuses'},
        ),
        migrations.AddIndex(
            model_name='gpustatus',
            index=models.Index(fields=['miner_status', 'number'], name='app_gpustat_miner_s_64ddf7_idx'),
        ),
    ]
