# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-19 01:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180219_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpustatus',
            name='miner_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gpus', to='app.MinerStatus', verbose_name='miner status record'),
        ),
    ]
