# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-20 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rig_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restrict_stats', models.BooleanField(default=False, help_text='restrict stats viewing to logged in users', verbose_name='restrict stats?')),
                ('restrict_actions', models.BooleanField(default=True, help_text='restrict actions (restart, etc.) to logged in users', verbose_name='restrict actions?')),
                ('warn_temp', models.PositiveIntegerField(default=55, help_text='value above which stats are displayed in yellow', verbose_name='warning temperature')),
                ('crit_temp', models.PositiveIntegerField(default=70, help_text='value above which stats are displayed in red', verbose_name='critical temperature')),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
    ]
