# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-20 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_siteconfiguration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteconfiguration',
            options={'verbose_name': 'site configuration'},
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='crit_temp',
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='danger_fan',
            field=models.PositiveIntegerField(default=75, help_text='value above which stats are displayed in red', verbose_name='danger fan %'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='danger_temp',
            field=models.PositiveIntegerField(default=70, help_text='value above which stats are displayed in red', verbose_name='danger temperature'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='warn_fan',
            field=models.PositiveIntegerField(default=60, help_text='value above which stats are displayed in yellow', verbose_name='warning fan %'),
        ),
    ]
