# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-24 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180220_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='minerstatus',
            name='error',
            field=models.CharField(blank=True, default=None, max_length=512, null=True, verbose_name='error'),
        ),
    ]
