# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-07 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_minerstatus_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rig',
            name='type',
            field=models.CharField(choices=[('claymore', 'Claymore')], default='claymore', max_length=10, verbose_name='miner type'),
        ),
        migrations.AddIndex(
            model_name='minerstatus',
            index=models.Index(fields=['miner', 'created_at'], name='app_minerst_miner_i_d9553d_idx'),
        ),
    ]
